### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ChasonMei** [littlewin-wang/hexo-theme-casual#4]
挺喜欢你的主题的，但是有一些问题和建议如下

1. archive 页，能否多展示几篇文章，并且字体放大一点，要是能加时间轴就更好了。
2. 搜索不能用，现在注册swifttype搜索好麻烦，注册不成功。
3. code高亮颜色主题是否可以更换，想换个类似于sublimetext主题的那种。

**Comment by littlewin-wang** [comment]
最近主题在大改中，谢谢你的建议，我会在新版本中逐一考虑

**Comment by littlewin-wang** [comment]
@ChasonMei 
博客主题已更新，你说的建议点有体现，可以试用下

**Comment by ChasonMei** [comment]
不错啊，还真是大改，这次的功能完整了很多，自学进步很快啊
