### ISSUE TITLE
主题安装不成功

### ISSUE THREAD

**Issue by Brania** [littlewin-wang/hexo-theme-casual#5]
Unhandled rejection TypeError: /Users/xxx/Hexo/blog/themes/casual/layout/mixins/post.jade:18
    16|             != full_date(item.date, 'll')
    17|           span.post-tag
  > 18|             a(href= url_for(item.tags.toArray()[0].path))
    19|               != item.tags.toArray()[0].name
    20|         h3.post-title
    21|           a(href= url_for(item.path))

Cannot read property 'path' of undefined
    at eval (eval at exports.compile (/Users/xxx/Hexo/blog/node_modules/jade/lib/index.js:218:8), <anonymous>:646:66)
    at Model._Query.Query.Query.forEach (/Users/xxx/Hexo/blog/node_modules/warehouse/lib/query.js:42:5)

**Comment by littlewin-wang** [comment]
有可能是文章没有标签，试着先在文章md里加入
```
tags: ["前端"]
```
试试呢

我会在此处加个判断来优化

**Comment by FengHaiSheng** [comment]
这个文章md在哪儿

**Comment by littlewin-wang** [comment]
就是自己写的markdown格式的文章，文章开头一般有
```
---
title: 「casual」主题更新记录
date: 2017-03-08 14:34:11
tags: ["前端"]
bgimage: http://7xpot0.com1.z0.glb.clouddn.com/17-3-8/99520617-file_1488955072521_84f3.png
---
```

**Comment by ChasonMei** [comment]
确实是hexo自带的那篇文章hello-world.md没有tags导致出错

**Comment by littlewin-wang** [comment]
Done with <https://github.com/littlewin-wang/hexo-theme-casual/commit/bf80e2303c511ec6b5f35455bdffecd0b2cc24d9>
